name: Push Specific File to Another Repo

on:
  workflow_dispatch:  # 手動実行を可能にする
  push:
    branches:
      - main  # mainブランチにpushされたら実行

jobs:
  sync-file:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source repository
        uses: actions/checkout@v4
        with:
          # ソースリポジトリの指定
          repository: 'compasstest-org/webhook-test'
          token: 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

      - name: Set up Git authentication
        run: |
          git config --global user.name "kaichi-ryunosuke"
          git config --global user.email "kaichi.ryunosuke.m7b@jp.nssol.nipponsteel.com"
          echo "https://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@github.com" > ~/.git-credentials
          git config --global credential.helper store

      - name: Clone destination repository
        run: |
          git clone https://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@github.com/compasstest-org/morimori.git temp-repo
          cd temp-repo
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Copy specific file to destination repository
        run: |
          # コピーしたいファイルを指定
          cp ../template.yaml ./

      - name: Commit and push changes
        run: |
          cd temp-repo
          git add path/to/destination/file.txt
          git commit -m "Add specific file to destination repository" || echo "No changes to commit"
          git push origin main
