name: Push Specific Files to Another Repo

on:
  workflow_dispatch:  # 手動実行を可能にする
  push:
    branches:
      - main  # mainブランチにpushされたら実行

jobs:
  sync-file:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source repository
        uses: actions/checkout@v4
        with:
          # ソースリポジトリの指定
          repository: 'compasstest-org/webhook-test'
          token: ${{ secrets.TOKEN }}
          path: source-repo  # source-repoという名前のディレクトリにチェックアウト

      - name: Checkout destination repository
        uses: actions/checkout@v4
        with:
          # ターゲットリポジトリの指定
          repository: 'compasstest-org/morimori'
          token: ${{ secrets.TOKEN }}
          path: destination-repo  # destination-repoという名前のディレクトリにチェックアウト

      - name: Set up Git authentication
        run: |
          git config --global user.name "kaichi-ryunosuke"
          git config --global user.email "kaichi.ryunosuke.m7b@jp.nssol.nipponsteel.com"
          echo "https://${{ secrets.TOKEN }}@github.com" > ~/.git-credentials
          git config --global credential.helper store

      - name: Copy all files from source to destination
        run: |
          # source-repo内のすべてのファイルをdestination-repoにコピー（フォルダ構成も含む）
          cp -r source-repo/.github/workflows/blank.yml destination-repo/.github/workflows/blank.yml

      - name: Commit and push changes
        run: |
          cd destination-repo
          git add .  # すべての変更をステージング
          git commit -m "Add files from source repository" || echo "No changes to commit"
          git push origin main
